//! F-2 cross-language parity lock (the kriya-console design doc f2-gates §2): evaluates the
//! committed `gate-matcher-vectors.json` corpus through `permissions::GatePolicy::evaluate` over
//! the committed `default-gates.yaml` — the SAME two files the kriya-console suite evaluates
//! through its TS compiler + evaluator (`test/gates.test.ts`). Both files are generated by the
//! Console's `scripts/gen-gate-vectors.mts` and committed byte-identical in both repos; a dialect
//! or semantics drift between the JS `RegExp` and `regex-lite` evaluations of the shared matcher
//! table surfaces HERE, as a vector mismatch — never silently in production.

use std::path::PathBuf;

use kriya::permissions::{GateDecision, Policy};
use serde_json::Value;

fn fixture(name: &str) -> String {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures").join(name);
    std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()))
}

#[test]
fn every_vector_agrees_with_the_console_evaluation() {
    let policy: Policy = serde_yaml::from_str(&fixture("default-gates.yaml")).expect("default-gates.yaml parses as a Policy");
    let gates = policy.gates().expect("the fixture policy carries a gates section");
    let vectors: Vec<Value> = serde_json::from_str(&fixture("gate-matcher-vectors.json")).expect("vectors parse");
    assert!(vectors.len() >= 20, "the vector corpus is non-trivial");

    for v in &vectors {
        let name = v["name"].as_str().unwrap();
        let tool_name = v["tool_name"].as_str().unwrap();
        let tool_input = &v["tool_input"];
        // The hook derives action_id as `claude-code__<tool lowercased>`; vectors don't assert on
        // it beyond presence, so the reconstruction here only needs to be consistent.
        let action_id = format!("claude-code__{}", tool_name.to_lowercase());

        let decision = gates.evaluate(tool_name, tool_input, &action_id);
        let got: Option<(String, String, String, String)> = match &decision {
            GateDecision::Pass => None,
            GateDecision::Receipt(r) => Some(("receipt".into(), r.class.clone(), r.rule_id.clone(), tier_str(r.tier))),
            GateDecision::Approval(r) => Some(("approval".into(), r.class.clone(), r.rule_id.clone(), tier_str(r.tier))),
            GateDecision::Deny(r) => Some(("deny".into(), r.class.clone(), r.rule_id.clone(), tier_str(r.tier))),
        };
        let want: Option<(String, String, String, String)> = if v["expect"].is_null() {
            None
        } else {
            Some((
                v["expect"]["kind"].as_str().unwrap().to_string(),
                v["expect"]["class"].as_str().unwrap().to_string(),
                v["expect"]["rule_id"].as_str().unwrap().to_string(),
                v["expect"]["tier"].as_str().unwrap().to_string(),
            ))
        };
        assert_eq!(got, want, "vector '{name}' diverged from the Console evaluation");
    }
}

fn tier_str(t: kriya::permissions::GateTier) -> String {
    serde_json::to_value(t).unwrap().as_str().unwrap().to_string()
}
